on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prep NPM dependencies
        run: npm ci

      - name: Test NPM test:unit
        run: npm run test:unit

      - name: SSH Action
        uses: invi5H/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
        run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
