on:
  push:
    branches:
      - master

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes_filter
        with:
          filters: |
            tests:
              - '**.js'
              - '**.vue'

      - name: Setup environment
        if: ${{ steps.changes_filter.outputs.tests == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        if: ${{ steps.changes_filter.outputs.tests == 'true' }}
        run: yarn install --frozen-lockfile

      - name: Run tests
        if: ${{ steps.changes_filter.outputs.tests == 'true' }}
        run: yarn test:unit

  rebuild:
    name: Rebuild
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild docker image on VPS
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.VPS_IP}}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASSWORD }}
          command: |
            bash /home/${{ secrets.VPS_USER }}/rebuild_diki_club.sh
