on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prep dependencies
        run: yarn install --frozen-lockfile

      - name: Test NPM test:unit
        run: yarn test:unit

      - name: Restart docker image on VPS
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.VPS_IP}}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASSWORD }}
          command: |
            bash /home/rebuild_diki_club.sh
