on:
  push:
    branches:
      - master

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      is_js_changed: ${{ steps.filter.outputs.is_js_changed }}
      need_rebuild: ${{ steps.filter.outputs.need_rebuild }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            is_js_changed:
              - '**.js'
              - '**.vue'
            
            need_rebuild:
              - '**.js'
              - '**.vue'
              - '**.less'
              - '**.html'
              - '**.png'

  test:
    name: Test
    needs: check-files
    if: ${{ needs.check-files.outputs.is_js_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prep dependencies
        run: yarn install --frozen-lockfile

      - name: Test NPM test:unit
        run: yarn test:unit

  rebuild:
    name: Rebuild
    needs: check-files
    if: ${{ needs.check-files.outputs.need_rebuild == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Restart docker image on VPS
        uses: fifsky/ssh-action@master
        with:
          host: ${{secrets.VPS_IP}}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASSWORD }}
          command: |
            bash /home/${{ secrets.VPS_USER }}/rebuild_diki_club.sh
