on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prep dependencies
        run: yarn install --frozen-lockfile

      - name: Test NPM test:unit
        run: yarn test:unit

#      - name: Deploy App and Deploy
#        uses: appleboy/ssh-action@v0.1.2
#        with:
#          host: ${{secrets.VPS_IP}}
#          username: ${{ secrets.VPS_USER }}
#          password: ${{ secrets.VPS_PASSWORD }}
#          script: |
#            rb_diki_club

      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls && pwd && cd /var/www/html/my-visit-card
          host: ${{secrets.VPS_IP}}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASSWORD }}
